; Copyright (c) 2026 Nelaric

[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Engine/Maps/Entry
ServerDefaultMap=/Engine/Maps/Entry
GlobalDefaultGameMode=/Script/NelaricFoundation.NelaricGameModeBase

[/Script/Engine.Engine]
WorldSettingsClassName=/Script/NelaricFoundation.NelaricWorldSettings

[CoreRedirects]
+ClassRedirects=(OldName="/Script/NelaricGameplayCore.NelaricGameModeBase",NewName="/Script/NelaricFoundation.NelaricGameModeBase")
+ClassRedirects=(OldName="/Script/NelaricGameplayCore.NelaricWorldSettings",NewName="/Script/NelaricFoundation.NelaricWorldSettings")
+ClassRedirects=(OldName="/Script/NelaricGameplayCore.NelaricPlayerController",NewName="/Script/NelaricFoundation.NelaricPlayerController")
+ClassRedirects=(OldName="/Script/NelaricGameplayCore.NelaricTransitionBeaconHost",NewName="/Script/NelaricFoundation.NelaricTransitionBeaconHost")
+ClassRedirects=(OldName="/Script/NelaricGameplayCore.NelaricTransitionBeaconClient",NewName="/Script/NelaricFoundation.NelaricTransitionBeaconClient")
+ClassRedirects=(OldName="/Script/NelaricGameplayCore.NelaricTransitionTransportSubsystem",NewName="/Script/NelaricFoundation.NelaricTransitionTransportSubsystem")
