; Copyright (c) 2026 Nelaric Contributors

[/Script/GameplayTags.GameplayTagsSettings]
+GameplayTagRedirects=(OldTagName="InputTag.Move",NewTagName="InputTag.Character.Move")
+GameplayTagRedirects=(OldTagName="InputTag.Look.Mouse",NewTagName="InputTag.Character.Look.Mouse")
+GameplayTagRedirects=(OldTagName="InputTag.Look.Stick",NewTagName="InputTag.Character.Look.Stick")
+GameplayTagRedirects=(OldTagName="InputTag.Jump",NewTagName="InputTag.Character.Jump")
