; Copyright (c) 2026 Nelaric Contributors

[/Script/EngineSettings.GeneralProjectSettings]
ProjectName=Nelaric Gameplay
ProjectID=89F6A2844FA559FF6F32019E4E36F3C0

[/Script/UnrealEd.ProjectPackagingSettings]
+DirectoriesToAlwaysStageAsUFS=(Path="JavaScript")

[/Script/GameplayAbilities.AbilitySystemGlobals]
+GameplayCueNotifyPaths=/Game/Demo
