; Copyright (c) 2026 Nelaric Contributors

[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Game/Demo/Levels/Demo1_Test/Demo1_Test.Demo1_Test
ServerDefaultMap=/Engine/Maps/Entry
GlobalDefaultGameMode=/Script/DemoGame.DemoGameMode
GameInstanceClass=/Script/DemoGame.DemoGameInstance
EditorStartupMap=/Game/Demo/Levels/Demo1_Test/Demo1_Test.Demo1_Test

[/Script/Engine.Engine]
WorldSettingsClassName=/Script/GameplayRuntime.NelaricWorldSettings

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=
