; Copyright (c) 2026 Nelaric

[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Engine/Maps/Entry
ServerDefaultMap=/Engine/Maps/Entry

[/Script/Engine.Engine]
WorldSettingsClassName=/Script/NelaricGameplayCore.NelaricWorldSettings
