// Copyright (c) 2026 Nelaric Contributors

#pragma once
#include "NativeGameplayTags.h"

namespace Nelaric::Soldier
{
UE_DECLARE_GAMEPLAY_TAG_EXTERN(EnemySeen);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(EnemyLost);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TargetChanged);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TargetDead);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(SoundHeard);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damaged);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(NearMiss);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GrenadeDanger);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(MoveCompleted);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(MoveFailed);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(ReloadCompleted);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(BurstCompleted);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(OrderChanged);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(OrderCompleted);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(OrderFailed);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(DecisionChanged);
} // namespace Nelaric::Soldier
